### ISSUE TITLE
Generating labels for DAT/DADA

### ISSUE THREAD

**Issue by leonardltk** [JiJiJiang/ASV-Anti-Spoofing-DADA#4]
Hi, i followed ur scripts to generate features, but i only have generation of the normal labels. 
```
data/ASV17/labels/train_dev.txt
```

How do i generate labels for the DAT-DADA ?
```
data/ASV17/labels/train_dev_DAT-DADA.txt
```

**Comment by JiJiJiang** [comment]
Hey, DAT-DATA label file is only needed by ASV17+BTAS16-PA mixed dataset. As shown below, you need another column to represent the corresponding dataset information for each line. 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/23723621/157675037-e658ab74-9b1d-4558-92ca-e0a2ed5ef2e2.png">
<img width="782" alt="image" src="https://user-images.githubusercontent.com/23723621/157675157-92523bfc-58a2-41e1-92d3-815d4c31d365.png">

**Comment by leonardltk** [comment]
which means, 
1. if im only using ASV17 to train, i dont need DAT-DADA labels, since the is no domain mismatch?
2. if im using ASV17 + ASV19/Some-other-datasets, then i will need DAT-DADA labels right?

**Comment by JiJiJiang** [comment]
Yes, exactly. For a mixed dataset, we need the DAT-DADA label file to train a DAT/DADA model. 

By the way, we do not suggest using the ASV19 dataset to train a DAT/DADA model. Since ASV19 PA data are all simulated rather than recorded in real devices, their data distribution is quite different from real dataset (such as ASV17 and BTAS 16).

**Comment by leonardltk** [comment]
Oh, i didnt realise that. thanks for the headsup !

**Comment by leonardltk** [comment]
Hi, 

in our other conversation, you mentioned this.
```
In training, we have only two datasets:
Dataset A: source-domain, with spoofing label: bonafide/spoof
Dataset B: target-domain, without spoofing label.
We have two domain discriminator branches in the model: one for spoofing data and the other for bonafide data.

Source-domain: we have the spoofing label, so we know which domain discriminator should be trained.
Target-domain: we do not have the spoofing label, so we use the spoofing detector to predict whether it is spoofed or bonafide. During training, we can get its bonafide probability, and train both domain discriminators at the same time.
```

However in your template `ASV17+BTAS16-PA` labels, both show spoof/bonafide labels.

May i know how to proceed with the dataset script with a dataset that does not have spoofing labels?

**Comment by JiJiJiang** [comment]
> Hi,
> 
> in our other conversation, you mentioned this.
> 
> ```
> In training, we have only two datasets:
> Dataset A: source-domain, with spoofing label: bonafide/spoof
> Dataset B: target-domain, without spoofing label.
> We have two domain discriminator branches in the model: one for spoofing data and the other for bonafide data.
> 
> Source-domain: we have the spoofing label, so we know which domain discriminator should be trained.
> Target-domain: we do not have the spoofing label, so we use the spoofing detector to predict whether it is spoofed or bonafide. During training, we can get its bonafide probability, and train both domain discriminators at the same time.
> ```
> 
> However in your template `ASV17+BTAS16-PA` labels, both show spoof/bonafide labels.
> 
> May i know how to proceed with the dataset script with a dataset that does not have spoofing labels?

Hi, sorry to let you wait for a long time.

As you mention above, I template ASV17+BTAS16-PA with both spoof/bonafide labels. That is actually for convenience, because
I can use the same label file whether ASV17 is source-domain or BTAS16-PA is source-domain in training. I don't use the spoof/bonafile labels for target-domain data although the labels are provided in the label file.

So,  for a dataset that does not have spoofing labels, just use any puppet symbol to fill in the label (not used in training !!!). I believe model training is still fine.
